name: Continuous integration

on: [push]

jobs:
  clippy_and_test:
    name: Clippy and test
    runs-on: ubuntu-latest
    env:
      LLVM_CONFIG_PATH: /usr/lib/llvm-9/bin/llvm-config
      IMAGEMAGICK_VERSION: 7.0.10-2
    steps:
      - name: Install ImageMagick 7
        run: |
          cd /tmp
          wget https://imagemagick.org/download/releases/ImageMagick-${IMAGEMAGICK_VERSION}.tar.gz
          tar xvzf ImageMagick-${IMAGEMAGICK_VERSION}.tar.gz
          cd ImageMagick-${IMAGEMAGICK_VERSION}
          ./configure
          make
          sudo make install
          sudo ldconfig /usr/local/lib

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace
